/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/catalog/tables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Catalog Tables */
    get: operations["list_catalog_tables_api_v1_catalog_tables_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/tables/{table_name}/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Catalog Table Summary */
    get: operations["read_catalog_table_summary_api_v1_catalog_tables__table_name__summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Config */
    get: operations["read_config_api_v1_config_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/curation/pin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pin Manifest */
    post: operations["pin_manifest_api_v1_curation_pin_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/curation/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Curation Preview */
    post: operations["run_curation_preview_api_v1_curation_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/curation/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Curation Report */
    post: operations["run_curation_report_api_v1_curation_report_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Episodes */
    get: operations["list_episodes_api_v1_episodes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes/facets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Episode Facets */
    get: operations["read_episode_facets_api_v1_episodes_facets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Episode Stats */
    get: operations["read_episode_stats_api_v1_episodes_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes/{episode_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Episode */
    get: operations["read_episode_api_v1_episodes__episode_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes/{episode_id}/canonical": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Episode Canonical */
    get: operations["read_episode_canonical_api_v1_episodes__episode_id__canonical_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes/{episode_id}/media/{artifact_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Episode Media */
    get: operations["read_episode_media_api_v1_episodes__episode_id__media__artifact_name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/episodes/{episode_id}/timeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Episode Timeline */
    get: operations["read_episode_timeline_api_v1_episodes__episode_id__timeline_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Health */
    get: operations["read_health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/manifests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Manifests */
    get: operations["list_manifests_api_v1_manifests_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/manifests/{manifest_id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download Manifest */
    get: operations["download_manifest_api_v1_manifests__manifest_id__download_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pipeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Pipeline */
    get: operations["read_pipeline_api_v1_pipeline_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pipeline/graph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read Pipeline Graph
     * @description The merged picture: the DAG topology plus the pipeline's user steps.
     *
     *     Three degraded states, each explicit rather than an error: no runtime
     *     addressed (``dag_ids_known: false``, display-only ids), no
     *     ``--pipeline`` (``steps_known: false``, no user steps and no
     *     quarantine gate), and both at once -- the common first-run case.
     */
    get: operations["read_pipeline_graph_api_v1_pipeline_graph_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/queries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Saved Queries */
    get: operations["list_saved_queries_api_v1_queries_get"];
    put?: never;
    /** Create Saved Query */
    post: operations["create_saved_query_api_v1_queries_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/queries/{query_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Saved Query */
    put: operations["update_saved_query_api_v1_queries__query_id__put"];
    post?: never;
    /** Delete Saved Query */
    delete: operations["delete_saved_query_api_v1_queries__query_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runtime/ingest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger Ingest */
    post: operations["trigger_ingest_api_v1_runtime_ingest_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runtime/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Runtime Runs */
    get: operations["list_runtime_runs_api_v1_runtime_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runtime/runs/{dag_run_id}/graph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read Run Graph
     * @description One master run's live state over the same topology.
     *
     *     The master run is addressed directly; each stage's sub-DAG run is
     *     resolved by the documented heuristic in :func:`_matched_stage_run`.
     */
    get: operations["read_run_graph_api_v1_runtime_runs__dag_run_id__graph_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runtime/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Runtime Status */
    get: operations["read_runtime_status_api_v1_runtime_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CatalogTableDescription
     * @description One browsable catalog relation and its live columns.
     */
    CatalogTableDescription: {
      /** Columns */
      columns: components["schemas"]["ColumnDescriptor"][];
      /**
       * Kind
       * @enum {string}
       */
      kind: "view" | "table";
      /** Name */
      name: string;
    };
    /**
     * CatalogTableSummaryResponse
     * @description One relation's row count and DuckDB's own column profile.
     */
    CatalogTableSummaryResponse: {
      /**
       * Columns
       * @description DuckDB SUMMARIZE rows; see CurationPreviewResponse.column_stats.
       */
      columns: {
        [key: string]: unknown;
      }[];
      /** Row Count */
      row_count: number;
    };
    /** CatalogTablesResponse */
    CatalogTablesResponse: {
      /** Tables */
      tables: components["schemas"]["CatalogTableDescription"][];
    };
    /**
     * CategoricalColumnStats
     * @description A low-cardinality column's top values under the current filters.
     */
    CategoricalColumnStats: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "categorical";
      /** Name */
      name: string;
      /**
       * Other Count
       * @description Non-null rows beyond the served top values.
       */
      other_count: number;
      /** Values */
      values: components["schemas"]["ValueCount"][];
    };
    /**
     * CheckCoverageEntry
     * @description One check's coverage denominator over the WHOLE catalog, not the cut.
     *
     *     Also the sidecar's stored shape, nested inside every stored manifest
     *     entry's ``coverage`` (see the module note).
     */
    CheckCoverageEntry: {
      /** Check Name */
      check_name: string;
      /** Episodes Ran */
      episodes_ran: number;
      /** Fraction */
      fraction: number;
      /** Total Episodes */
      total_episodes: number;
    };
    /**
     * ColumnDescriptor
     * @description One result column as DuckDB's ``DESCRIBE`` reports it.
     */
    ColumnDescriptor: {
      /** Name */
      name: string;
      /** Type */
      type: string;
    };
    /**
     * CurationPreviewResponse
     * @description A user SELECT's first rows, its full count, and optional column stats.
     */
    CurationPreviewResponse: {
      /**
       * Column Stats
       * @description DuckDB SUMMARIZE rows (column_name, column_type, min, max, null_percentage, ...). DuckDB owns that shape and varies it by version, so it is served as-is. Null unless the request asked for stats.
       */
      column_stats:
        | {
            [key: string]: unknown;
          }[]
        | null;
      /** Columns */
      columns: components["schemas"]["ColumnDescriptor"][];
      /**
       * Row Count
       * @description Rows the SELECT returns in full, independent of limit.
       */
      row_count: number;
      /**
       * Rows
       * @description Rows of the user's own SELECT; its columns are described by 'columns'.
       */
      rows: {
        [key: string]: unknown;
      }[];
      /**
       * Sql
       * @description The logical wrapped SELECT, copy-pastable as-is. The executed statement adds a '* REPLACE (...)' projection rendering TIMESTAMPTZ columns as UTC ISO text (the locked connection cannot SET TimeZone), which is a rendering detail of these rows rather than part of the query a user wrote.
       */
      sql: string;
      /** Truncated */
      truncated: boolean;
    };
    /**
     * CurationReportResponse
     * @description What a cut would contain, and what evidence backs it -- no files written.
     */
    CurationReportResponse: {
      /** Coverage */
      coverage: components["schemas"]["CheckCoverageEntry"][];
      /** Row Count */
      row_count: number;
      /** Total Episodes */
      total_episodes: number;
    };
    /**
     * DagTaskNodePayload
     * @description One task of a generated DAG (mirrors ``hflow.runtime.DagTaskNode``).
     */
    DagTaskNodePayload: {
      /**
       * Deferred
       * @description Defers instead of holding a worker slot.
       */
      deferred: boolean;
      /**
       * Mapped
       * @description Dynamically mapped: one instance per planned batch.
       */
      mapped: boolean;
      /** Summary */
      summary: string;
      /** Task Id */
      task_id: string;
    };
    /**
     * DagTopologyPayload
     * @description One DAG's real shape: its tasks and their real dependency edges.
     */
    DagTopologyPayload: {
      /** Dag Id */
      dag_id: string;
      /**
       * Edges
       * @description [upstream, downstream] task-id pairs, in declaration order.
       */
      edges: [string, string][];
      /** Tasks */
      tasks: components["schemas"]["DagTaskNodePayload"][];
    };
    /**
     * DossierEpisode
     * @description The episode's own ``episodes_latest`` row plus the two derived fields.
     *
     *     ``extra="allow"``: every column of that row rides along unchanged, because
     *     the catalog's columns are data this module cannot enumerate.
     */
    DossierEpisode: {
      /**
       * Quarantine Tags
       * @description Parsed out of the row's quarantine_tags_json; empty when not quarantined.
       */
      quarantine_tags: string[];
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "quarantined";
    } & {
      [key: string]: unknown;
    };
    /**
     * EpisodeCheckRunRecord
     * @description One recorded check invocation.
     */
    EpisodeCheckRunRecord: {
      /** Check Name */
      check_name: string | null;
      /** Check Version */
      check_version: string | null;
      /** Critical */
      critical: boolean | null;
      /** Duration S */
      duration_s: number | null;
      /** Error */
      error: string | null;
      /** Recorded At */
      recorded_at: string | null;
      /** Run Fingerprint */
      run_fingerprint: string | null;
      /** Status */
      status: string | null;
    };
    /**
     * EpisodeDossierResponse
     * @description Everything the episode page shows for one episode.
     */
    EpisodeDossierResponse: {
      /** Canonical Url */
      canonical_url: string | null;
      /** Check Runs */
      check_runs: components["schemas"]["EpisodeCheckRunRecord"][];
      episode: components["schemas"]["DossierEpisode"];
      /**
       * History
       * @description Every append of this episode, newest first: raw episodes_raw rows, whose columns are the catalog's (see EpisodePageResponse.rows).
       */
      history: {
        [key: string]: unknown;
      }[];
      /** Intervals */
      intervals: components["schemas"]["EpisodeIntervalRecord"][];
      /** Measurements */
      measurements: components["schemas"]["EpisodeMeasurementRecord"][];
      /** Media */
      media: components["schemas"]["EpisodeMediaArtifact"][];
      /** Tags */
      tags: components["schemas"]["EpisodeTagRecord"][];
    };
    /**
     * EpisodeFacetsResponse
     * @description Facet value counts over the wide episodes view; NULL buckets skipped.
     *
     *     This model is the one owner of WHICH columns are faceted: ``_catalog``
     *     reads the column list off these fields rather than restating it.
     */
    EpisodeFacetsResponse: {
      /** Embodiment */
      embodiment: components["schemas"]["ValueCount"][];
      /** Operator */
      operator: components["schemas"]["ValueCount"][];
      /** Pipeline Version */
      pipeline_version: components["schemas"]["ValueCount"][];
      /** Status */
      status: components["schemas"]["ValueCount"][];
      /** Task */
      task: components["schemas"]["ValueCount"][];
    };
    /**
     * EpisodeIntervalRecord
     * @description One interval of the episode's LATEST run.
     *
     *     ``check_version`` rides in from that run's ``check_runs`` row (a LEFT
     *     JOIN -- the intervals table carries no version of its own).
     */
    EpisodeIntervalRecord: {
      /** Check Name */
      check_name: string | null;
      /** Check Version */
      check_version: string | null;
      /** End Ns */
      end_ns: number | null;
      /** Label */
      label: string | null;
      /** Start Ns */
      start_ns: number | null;
    };
    /**
     * EpisodeMeasurementRecord
     * @description One measurement, latest per key.
     */
    EpisodeMeasurementRecord: {
      /** Check Name */
      check_name: string | null;
      /** Check Version */
      check_version: string | null;
      /** Key */
      key: string | null;
      /** Recorded At */
      recorded_at: string | null;
      /** Value Bool */
      value_bool: boolean | null;
      /** Value Double */
      value_double: number | null;
      /** Value Text */
      value_text: string | null;
    };
    /**
     * EpisodeMediaArtifact
     * @description One cataloged media artifact and, when servable, its byte URL.
     */
    EpisodeMediaArtifact: {
      /** Name */
      name: string;
      /** Uri */
      uri: string;
      /**
       * Url
       * @description Same-origin byte-serving path, or null when the cataloged file is missing or lands outside the workspace data root.
       */
      url: string | null;
    };
    /**
     * EpisodePageResponse
     * @description One filtered, ordered page of the wide ``episodes`` view.
     */
    EpisodePageResponse: {
      /** Columns */
      columns: components["schemas"]["ColumnDescriptor"][];
      /**
       * Rows
       * @description Rows of the wide episodes view. Its columns are data (one per measurement key present at open time), so they are described by 'columns' rather than enumerated here.
       */
      rows: {
        [key: string]: unknown;
      }[];
      /**
       * Sql
       * @description The SELECT compiled for exactly these filters, with values inlined so it is copy-pastable and runs against the same catalog.
       */
      sql: string;
      /**
       * Total
       * @description Rows matching the SAME filters, ignoring limit/offset.
       */
      total: number;
    };
    /**
     * EpisodeStatsResponse
     * @description Per-column mini-distributions; degenerate columns are omitted entirely.
     */
    EpisodeStatsResponse: {
      /** Columns */
      columns: (
        | components["schemas"]["NumericColumnStats"]
        | components["schemas"]["CategoricalColumnStats"]
      )[];
    };
    /**
     * EpisodeTagRecord
     * @description One tag of the episode's LATEST run.
     */
    EpisodeTagRecord: {
      /** Check Name */
      check_name: string | null;
      /** Recorded At */
      recorded_at: string | null;
      /** Tag */
      tag: string | null;
    };
    /**
     * EpisodeTimelineResponse
     * @description One episode's time axis. All-null bounds mean the span is unknown --
     *     a client must say so rather than draw a fabricated axis.
     */
    EpisodeTimelineResponse: {
      /** Duration S */
      duration_s: number | null;
      /** End Ns */
      end_ns: number | null;
      /** Intervals */
      intervals: components["schemas"]["TimelineInterval"][];
      /** Measurements */
      measurements: components["schemas"]["TimelineMeasurement"][];
      /** Start Ns */
      start_ns: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description The liveness answer: the cheapest endpoint a probe can poll.
     */
    HealthResponse: {
      /** Ok */
      ok: boolean;
    };
    /** IngestRequest */
    IngestRequest: {
      /** Batch Count */
      batch_count?: number | null;
      /**
       * Mode
       * @default batch
       */
      mode: string;
      /**
       * Profile
       * @default full
       */
      profile: string;
      /** Uris */
      uris: string[];
    };
    /**
     * IngestTriggerResponse
     * @description What Airflow answered when the run was triggered.
     */
    IngestTriggerResponse: {
      /** Dag Run Id */
      dag_run_id: string | null;
      /** State */
      state: string | null;
    };
    /**
     * MappedFanOutSummary
     * @description The fan-out's live split, counted server-side over EVERY mapped instance.
     *
     *     Complete on its own: ``by_state`` partitions all ``total`` instances of
     *     ``task_id`` (an instance Airflow has not scheduled yet counts under
     *     ``no_status``), so ``total == sum(by_state.values())`` always holds and a
     *     client never has to recount the raw instances to size or colour the
     *     fan-out. Only a replay at some earlier instant is a different fact, and
     *     that one the server cannot answer.
     */
    MappedFanOutSummary: {
      /** By State */
      by_state: {
        [key: string]: number;
      };
      /** Task Id */
      task_id: string;
      /**
       * Total
       * @description Instances reported for the mapped task. Before the fan-out expands Airflow reports one unexpanded instance, which is counted -- that is the truth at that moment.
       */
      total: number;
    };
    /**
     * NumericColumnStats
     * @description A numeric column's mini-distribution under the current filters.
     */
    NumericColumnStats: {
      /** Buckets */
      buckets: components["schemas"]["NumericHistogramBucket"][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "numeric";
      /** Name */
      name: string;
    };
    /**
     * NumericHistogramBucket
     * @description One histogram bucket: ``lo`` inclusive, ``hi`` inclusive on the last.
     */
    NumericHistogramBucket: {
      /** Count */
      count: number;
      /** Hi */
      hi: number;
      /** Lo */
      lo: number;
    };
    /**
     * ObservedCheckVersion
     * @description What the catalog has SEEN of one (check, version) pair.
     */
    ObservedCheckVersion: {
      /** Check Name */
      check_name: string | null;
      /** Check Version */
      check_version: string | null;
      /** First Seen */
      first_seen: string | null;
      /** Last Seen */
      last_seen: string | null;
      /** Run Count */
      run_count: number;
    };
    /** PinRequest */
    PinRequest: {
      /**
       * Description
       * @default
       */
      description: string;
      /** Name */
      name: string;
      /** Sql */
      sql: string;
    };
    /**
     * PinnedManifestEntry
     * @description One registry entry for an immutable pinned manifest file.
     *
     *     Also the sidecar's stored shape for a manifest (see the module note).
     */
    PinnedManifestEntry: {
      /**
       * Coverage
       * @description Frozen at pin time.
       */
      coverage: components["schemas"]["CheckCoverageEntry"][];
      /**
       * Created At
       * @description ISO-8601 UTC.
       */
      created_at: string;
      /** Description */
      description: string;
      /** Id */
      id: string;
      /**
       * Manifest Path
       * @description Data-root-relative, e.g. 'manifests/<slug>-<utc timestamp>.parquet'.
       */
      manifest_path: string;
      /** Name */
      name: string;
      /** Row Count */
      row_count: number;
      /** Sql */
      sql: string;
      /** Total Episodes */
      total_episodes: number;
    };
    /** PinnedManifestListResponse */
    PinnedManifestListResponse: {
      /** Manifests */
      manifests: components["schemas"]["PinnedManifestEntry"][];
    };
    /**
     * PipelineEngineStep
     * @description Engine work inside one stage that no manifest lists.
     */
    PipelineEngineStep: {
      /** Name */
      name: string;
      /** Summary */
      summary: string;
    };
    /**
     * PipelineGraphResponse
     * @description The ingest DAG's shape merged with the pipeline's own steps.
     */
    PipelineGraphResponse: {
      /**
       * Dag Ids Known
       * @description False when no runtime is addressed: the dag ids are display-only.
       */
      dag_ids_known: boolean;
      master: components["schemas"]["DagTopologyPayload"];
      /** @description Null exactly when steps_known is false. */
      quarantine_gate: components["schemas"]["QuarantineGate"] | null;
      /** Stages */
      stages: components["schemas"]["PipelineGraphStage"][];
      /**
       * Steps Known
       * @description False without --pipeline: what runs inside process_batch is unknown.
       */
      steps_known: boolean;
    };
    /**
     * PipelineGraphStage
     * @description One stage lane of the pipeline graph: its DAG plus what runs inside it.
     */
    PipelineGraphStage: {
      dag: components["schemas"]["DagTopologyPayload"];
      /** Description */
      description: string;
      /** Enabling Profiles */
      enabling_profiles: string[];
      /** Engine Steps */
      engine_steps: components["schemas"]["PipelineEngineStep"][];
      /** Gate Task Id */
      gate_task_id: string;
      stage: components["schemas"]["Stage"];
      /** Title */
      title: string;
      /** Trigger Task Id */
      trigger_task_id: string;
      /** User Steps */
      user_steps: components["schemas"]["PipelineUserStep"][];
    };
    /**
     * PipelineResponse
     * @description The startup-imported App, described over this workspace's catalog.
     */
    PipelineResponse: {
      /**
       * Manifest
       * @description The pipeline manifest exactly as hflow.manifest.PipelineManifest renders it. hflow.manifest owns that shape and stamps it with 'manifest_version', so it is forwarded rather than mirrored here.
       */
      manifest: {
        [key: string]: unknown;
      };
      /** Observed */
      observed: components["schemas"]["ObservedCheckVersion"][];
      /** @description Null when staleness is unknowable (no catalog yet). */
      stale: components["schemas"]["StaleSummary"] | null;
    };
    /**
     * PipelineUserStep
     * @description A registered step as the graph endpoint serves it.
     *
     *     ``tier`` mirrors ``hflow.App._ordered_checks``: tier 2 is exactly the steps
     *     declaring ``requires`` or ``uses``. Steps within a tier have NO ordering.
     */
    PipelineUserStep: {
      /** Critical */
      critical: boolean;
      kind: components["schemas"]["StepKind"];
      /** Name */
      name: string;
      /** Requires */
      requires: string[];
      /**
       * Tier
       * @enum {integer}
       */
      tier: 1 | 2;
      /** Uses */
      uses: string | null;
      /**
       * Version
       * @description Content hash of the live function.
       */
      version: string;
    };
    /** PreviewRequest */
    PreviewRequest: {
      /**
       * Limit
       * @default 100
       */
      limit: number;
      /** Sql */
      sql: string;
      /**
       * Stats
       * @default false
       */
      stats: boolean;
    };
    /**
     * QuarantineGate
     * @description The one real cross-step edge, served as its own object rather than as
     *     an edge in either graph.
     */
    QuarantineGate: {
      /** Critical Step Names */
      critical_step_names: string[];
      /** Explanation */
      explanation: string;
      from_stage: components["schemas"]["Stage"];
      /** To Stages */
      to_stages: components["schemas"]["Stage"][];
    };
    /** ReportRequest */
    ReportRequest: {
      /** Sql */
      sql: string;
    };
    /**
     * RunGraphMaster
     * @description The master run's own live state.
     */
    RunGraphMaster: {
      /** Dag Run Id */
      dag_run_id: string;
      /** State */
      state: string | null;
      /** Tasks */
      tasks: components["schemas"]["RunTaskInstance"][];
    };
    /**
     * RunGraphResponse
     * @description One master run's live state over the ingest topology.
     */
    RunGraphResponse: {
      master: components["schemas"]["RunGraphMaster"];
      /** Stages */
      stages: components["schemas"]["RunGraphStage"][];
    };
    /**
     * RunGraphStage
     * @description One stage's live state for this master run, or explicit nulls when the
     *     stage never ran for it.
     */
    RunGraphStage: {
      /** Dag Id */
      dag_id: string;
      /** Dag Run Id */
      dag_run_id: string | null;
      mapped_summary: components["schemas"]["MappedFanOutSummary"] | null;
      /**
       * Match
       * @description How this stage run was attributed to the master run. Airflow stores no parent-run link, so the only honest answer is 'heuristic' -- the earliest stage run started inside this master run's own window -- or null (nothing matched). Two master runs OVERLAPPING in time can still be attributed the same stage run.
       */
      match: "heuristic" | null;
      stage: components["schemas"]["Stage"];
      /** State */
      state: string | null;
      /** Tasks */
      tasks: components["schemas"]["RunTaskInstance"][];
    };
    /**
     * RunTaskInstance
     * @description One Airflow task instance, reduced to what the graph draws.
     */
    RunTaskInstance: {
      /** Duration S */
      duration_s: number | null;
      /** End Date */
      end_date: string | null;
      /**
       * Map Index
       * @description -1 means the task is not mapped.
       */
      map_index: number;
      /**
       * Queued At
       * @description When the scheduler queued the task, so a replay can tell 'waiting for a worker' from 'running'. Airflow may omit it.
       */
      queued_at: string | null;
      /** Start Date */
      start_date: string | null;
      /** State */
      state: string | null;
      /** Task Id */
      task_id: string | null;
      /** Try Number */
      try_number: number | null;
    };
    /**
     * RuntimeHealthComponents
     * @description Airflow's per-component health.
     *
     *     This model is the one owner of WHICH components /runtime/status reports:
     *     ``_runtime`` reads the names off these fields. A component absent from the
     *     deployment (a minimal stack runs no triggerer) reports null.
     */
    RuntimeHealthComponents: {
      /** Dag Processor */
      dag_processor: string | null;
      /** Metadatabase */
      metadatabase: string | null;
      /** Scheduler */
      scheduler: string | null;
      /** Triggerer */
      triggerer: string | null;
    };
    /**
     * RuntimeRunSummary
     * @description One master DAG run, reduced to what the Runs page shows.
     */
    RuntimeRunSummary: {
      /**
       * Conf
       * @description The trigger's own input, forwarded verbatim.
       */
      conf: {
        [key: string]: unknown;
      };
      /** Dag Run Id */
      dag_run_id: string | null;
      /** End Date */
      end_date: string | null;
      /** Logical Date */
      logical_date: string | null;
      /** Start Date */
      start_date: string | null;
      /** State */
      state: string | null;
    };
    /** RuntimeRunsResponse */
    RuntimeRunsResponse: {
      /** Runs */
      runs: components["schemas"]["RuntimeRunSummary"][];
      /**
       * Stages
       * @description Per-stage recent runs; null for a remote runtime, whose stage sub-DAG ids only a bundle manifest records.
       */
      stages: components["schemas"]["StageRecentRuns"][] | null;
    };
    /**
     * RuntimeStatusResponse
     * @description Whether this workspace's ingest runtime is addressed AND answering.
     *
     *     Every field except ``available`` defaults to "not known", so an
     *     unavailable answer states only the facts it actually has -- there is no
     *     second hand-written shape for the unavailable case to drift from.
     */
    RuntimeStatusResponse: {
      /**
       * Airflow Web Url
       * @description Deep-link base for the Airflow web UI, AS ADDRESSED FROM THE WORKSPACE HOST. Only a local bundle records its own address; a remote endpoint's is unknown, never guessed.
       */
      airflow_web_url?: string | null;
      /**
       * Airflow Web Url Host Only
       * @description True when airflow_web_url is a loopback address, so it resolves only on the workspace host: a browser on another machine cannot follow it, and the runtime is reachable there only through a tunnel or a wider `hflow up --api-bind-host`.
       * @default false
       */
      airflow_web_url_host_only: boolean;
      /** Available */
      available: boolean;
      /** Dag Id */
      dag_id?: string | null;
      /**
       * Detail
       * @description Why the runtime is unavailable; null when it is available.
       */
      detail?: string | null;
      health?: components["schemas"]["RuntimeHealthComponents"] | null;
      /**
       * Registered
       * @description Whether the master DAG is registered. Null means unknown (an auth or transient failure), which is not the same as false.
       */
      registered?: boolean | null;
      /** Source */
      source?: ("bundle" | "remote") | null;
    };
    /** SavedQueryCreateRequest */
    SavedQueryCreateRequest: {
      /** Name */
      name: string;
      /** Sql */
      sql: string;
    };
    /**
     * SavedQueryEntry
     * @description One saved studio query.
     *
     *     Also the sidecar's stored shape for a saved query (see the module note).
     */
    SavedQueryEntry: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Sql */
      sql: string;
      /**
       * Updated At
       * @description ISO-8601 UTC.
       */
      updated_at: string;
    };
    /** SavedQueryListResponse */
    SavedQueryListResponse: {
      /** Queries */
      queries: components["schemas"]["SavedQueryEntry"][];
    };
    /** SavedQueryUpdateRequest */
    SavedQueryUpdateRequest: {
      /** Name */
      name?: string | null;
      /** Sql */
      sql?: string | null;
    };
    /**
     * Stage
     * @description The ingest stage graph's toggleable sub-DAGs, as stage names shared with the DAGs.
     *
     *     These strings are conf vocabulary: the master DAG resolves a run profile
     *     to a stage set and triggers only the sub-DAGs it names, and
     *     ``App.process(stages=...)`` runs the same set in-process. One owner --
     *     here -- so the runner and the DAG bundle can never disagree.
     * @enum {string}
     */
    Stage: "sync" | "meta" | "labels" | "media";
    /**
     * StageRecentRuns
     * @description One stage's most recent runs. NOT correlated with any master run.
     */
    StageRecentRuns: {
      /** Dag Id */
      dag_id: string;
      /** Recent */
      recent: components["schemas"]["StageRunSummary"][];
      stage: components["schemas"]["Stage"];
    };
    /**
     * StageRunSummary
     * @description One stage sub-DAG run in a stage's recent strip.
     */
    StageRunSummary: {
      /** Dag Run Id */
      dag_run_id: string | null;
      /** End Date */
      end_date: string | null;
      /** Start Date */
      start_date: string | null;
      /** State */
      state: string | null;
    };
    /**
     * StaleSummary
     * @description How many recorded episodes are stale against the App's current versions.
     */
    StaleSummary: {
      /** Count */
      count: number;
      /** Pipeline Version */
      pipeline_version: string;
    };
    /**
     * StepKind
     * @description Which registration surface a step came from.
     * @enum {string}
     */
    StepKind: "check" | "enrichment";
    /**
     * TimelineInterval
     * @description One interval placed on the episode's axis, in absolute ns and in
     *     seconds RELATIVE to the span start (both computed server-side).
     */
    TimelineInterval: {
      /** Check Name */
      check_name: string | null;
      /** End Ns */
      end_ns: number | null;
      /** End S */
      end_s: number | null;
      /**
       * Kind
       * @description Colour group: the label's '<kind>:<topic>' prefix, else the whole label, else the check that produced it.
       */
      kind: string;
      /** Label */
      label: string | null;
      /** Start Ns */
      start_ns: number | null;
      /** Start S */
      start_s: number | null;
    };
    /**
     * TimelineMeasurement
     * @description One numeric measurement, ready to draw as a bar.
     */
    TimelineMeasurement: {
      /** Key */
      key: string;
      /**
       * Unit
       * @description Inferred from the key's unit suffix; null when no dimension is known.
       */
      unit: string | null;
      /** Value */
      value: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * ValueCount
     * @description One value and how many episodes carry it.
     */
    ValueCount: {
      /** Count */
      count: number;
      /** Value */
      value: string;
    };
    /**
     * WorkspaceCapabilities
     * @description What this launch can actually do over this data root.
     *
     *     ``runtime`` means ADDRESSED (a rendered bundle or an exported remote URL),
     *     not reachable -- /runtime/status owns liveness.
     */
    WorkspaceCapabilities: {
      /** Catalog */
      catalog: boolean;
      /**
       * Curation
       * @description Whether the curation studio's durable state can be written at all: saved queries, the pinned-manifest registry, and the manifest files need a LOCAL data root, so a bucket-backed workspace answers 501 for every one of them and the frontend should not offer them.
       */
      curation: boolean;
      /** Media */
      media: boolean;
      /** Pipeline */
      pipeline: boolean;
      /** Runtime */
      runtime: boolean;
    };
    /**
     * WorkspaceConfigResponse
     * @description What this server is serving, and what the frontend may offer.
     *
     *     Deliberately carries no Airflow deep-link base: /runtime/status is the one
     *     owner of the runtime's addressing facts, including its web URL.
     */
    WorkspaceConfigResponse: {
      capabilities: components["schemas"]["WorkspaceCapabilities"];
      /** Data Root */
      data_root: string;
      /** Hflow Server Version */
      hflow_server_version: string;
      /** Hflow Version */
      hflow_version: string;
      /**
       * Ingest Modes
       * @description Live ingest modes from hflow.steps.IngestMode; same contract as run_profiles.
       */
      ingest_modes: string[];
      /**
       * Mode
       * @constant
       */
      mode: "local";
      /** Read Only */
      read_only: boolean;
      /**
       * Run Profiles
       * @description Live run-profile names from hflow.steps.RUN_PROFILES, served so the frontend never hardcodes them.
       */
      run_profiles: string[];
      /** Workspace Id */
      workspace_id: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_catalog_tables_api_v1_catalog_tables_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogTablesResponse"];
        };
      };
    };
  };
  read_catalog_table_summary_api_v1_catalog_tables__table_name__summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        table_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogTableSummaryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_config_api_v1_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceConfigResponse"];
        };
      };
    };
  };
  pin_manifest_api_v1_curation_pin_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PinRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PinnedManifestEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_curation_preview_api_v1_curation_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurationPreviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_curation_report_api_v1_curation_report_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurationReportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_episodes_api_v1_episodes_get: {
    parameters: {
      query?: {
        order_by?: string;
        order?: "asc" | "desc";
        limit?: number;
        offset?: number;
        task?: string[] | null;
        operator?: string[] | null;
        embodiment?: string[] | null;
        status?: ("ok" | "quarantined") | null;
        success?: ("true" | "false") | null;
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodePageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_episode_facets_api_v1_episodes_facets_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeFacetsResponse"];
        };
      };
    };
  };
  read_episode_stats_api_v1_episodes_stats_get: {
    parameters: {
      query?: {
        task?: string[] | null;
        operator?: string[] | null;
        embodiment?: string[] | null;
        status?: ("ok" | "quarantined") | null;
        success?: ("true" | "false") | null;
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeStatsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_episode_api_v1_episodes__episode_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        episode_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeDossierResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_episode_canonical_api_v1_episodes__episode_id__canonical_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        episode_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The file's bytes. An allowlisted inert media type (image, audio, video) is served inline under its own content type; anything else -- and every download -- is opaque application/octet-stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_episode_media_api_v1_episodes__episode_id__media__artifact_name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        episode_id: string;
        artifact_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The file's bytes. An allowlisted inert media type (image, audio, video) is served inline under its own content type; anything else -- and every download -- is opaque application/octet-stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_episode_timeline_api_v1_episodes__episode_id__timeline_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        episode_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeTimelineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  list_manifests_api_v1_manifests_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PinnedManifestListResponse"];
        };
      };
    };
  };
  download_manifest_api_v1_manifests__manifest_id__download_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        manifest_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The file's bytes. An allowlisted inert media type (image, audio, video) is served inline under its own content type; anything else -- and every download -- is opaque application/octet-stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_pipeline_api_v1_pipeline_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PipelineResponse"];
        };
      };
    };
  };
  read_pipeline_graph_api_v1_pipeline_graph_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PipelineGraphResponse"];
        };
      };
    };
  };
  list_saved_queries_api_v1_queries_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedQueryListResponse"];
        };
      };
    };
  };
  create_saved_query_api_v1_queries_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedQueryCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedQueryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_saved_query_api_v1_queries__query_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        query_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedQueryUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedQueryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_saved_query_api_v1_queries__query_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        query_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  trigger_ingest_api_v1_runtime_ingest_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestTriggerResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_runtime_runs_api_v1_runtime_runs_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuntimeRunsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_run_graph_api_v1_runtime_runs__dag_run_id__graph_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dag_run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunGraphResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_runtime_status_api_v1_runtime_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuntimeStatusResponse"];
        };
      };
    };
  };
}
